
-- CREATE TABLE IF NOT EXISTS public.agents
-- (
--     id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),

--     agent_code character varying(150) COLLATE pg_catalog."default" NOT NULL,
--     agent_name character varying(128) COLLATE pg_catalog."default" NOT NULL,
--     working_area character varying(254) COLLATE pg_catalog."default" NOT NULL,
--     commission numeric(10,2),
--     phone_number character varying(255) COLLATE pg_catalog."default",
--     country character varying(254) COLLATE pg_catalog."default" NOT NULL,
    
--     CONSTRAINT agents_pkey PRIMARY KEY (id),
--     CONSTRAINT agents_code_key UNIQUE (agent_code)
-- )


SELECT * FROM agents;   


-- TABLESPACE pg_default;


-- EXPLANATION.

-- id field

-- id integer NOT NULL: Defines a column named id with the data type integer that cannot be null.
-- GENERATED BY DEFAULT AS IDENTITY: This clause specifies that the id column is an identity column. 
    -- This is similar to the AUTO_INCREMENT feature in other databases.
-- INCREMENT 1: Specifies that the identity value will increment by 1 for each new row.
-- START 1: Specifies that the initial value of the identity column will start at 1.
-- MINVALUE 1: Sets the minimum value of the identity column to 1.
-- MAXVALUE 2147483647: Sets the maximum value of the identity column to 2147483647.
-- CACHE 1: Specifies how many sequence numbers are preallocated and stored in memory for faster access.

-- character field

-- agent_code character varying(150): Defines a column named agent_code with the data type character
    --  varying (string) with a maximum length of 150 characters.
-- COLLATE pg_catalog."default": Specifies the collation for the column, which determines how string 
    -- comparison is performed (e.g., sorting and case sensitivity).
-- NOT NULL: Specifies that the column cannot be null.

--  CONSTRAINTS
-- CONSTRAINT agents_pkey PRIMARY KEY (id): Defines a primary key constraint named agents_pkey on the id 
    -- column. The primary key uniquely identifies each record in the table and ensures that no two rows have the same id.
-- CONSTRAINT agents_code_key UNIQUE (agent_code): Defines a unique constraint named agents_code_key on the agent_code column. 
    -- This ensures that all values in the agent_code column are unique across the table.

-- TABLESPACE

-- TABLESPACE pg_default: Specifies that the table will be created in the default tablespace 
--     (pg_default). A tablespace is a location on disk where PostgreSQL stores the data files.